spring:
    datasource:
        url: jdbc:mysql://localhost:3307/database
        username: root
        password: XsLNBUvc5
    sql:
        init:
            mode: always
            schema-locations: classpath:schema.sql
